name: CAWeStruck
favicon: null
layout_spectrum: 0.42260705563239753
typography_spectrum: 0.9398702697362751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10481942351907492
  lightness: 0.8757916924078017
  saturation: 0.6771996021270752
  rhythmicContrast: 0.5285460653249174
purpose: []
